### ISSUE TITLE
Create a workflow to send templates to s3

### ISSUE THREAD

**Issue by 464d41** [f5devcentral/aws-waf-solution-template#17]
Create a workflow to send templates to s3.

Example of bucket structure: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=BigIp-Quickstart-Example&templateURL=https://f5-cft-v2.s3.amazonaws.com/f5-aws-cloudformation-v2/v1.0.1.0/examples/quickstart/quickstart.yaml

**Comment by yoctoalex** [comment]
done
